### ISSUE TITLE
Highlight bad for brackets and delimiters

### ISSUE THREAD

**Issue by jackhub** [stsewd/tree-sitter-comment#10]
<img width="380" alt="image" src="https://user-images.githubusercontent.com/4580635/149083206-b04ef46d-0549-4914-99c6-95947dbf08a2.png">

They should be greyed in comments, different with regulars.

**Comment by stsewd** [comment]
Hi, you can override the queries at https://github.com/nvim-treesitter/nvim-treesitter/blob/master/queries/comment/highlights.scm to change that to your like. See https://github.com/nvim-treesitter/nvim-treesitter#adding-queries.
