### ISSUE TITLE
Make trailing colon optional for all markers

### ISSUE THREAD

**Issue by erikw** [stsewd/tree-sitter-comment#13]
Hey, thanks for providing this parser!

There are some different styles out there for markers in common, two being e.g. `TODO` and `TODO:`. I noticed that this parser supports, which is great (I prefer the first to save one character).

However it seems like for the marker for notes, only `NOTE:` is detected but not `NOTE`, which I frequently use.  

Would it be possible to make the trailing colon optional for all markers?

**Comment by stsewd** [comment]
@erikw hi! you can already do this with a query, for example:

https://github.com/nvim-treesitter/nvim-treesitter/blob/9b13872f19aa97916ba0ae92bac6fb9e2c1dd06d/queries/comment/highlights.scm#L13-L14

The `text` node exposes all words that aren't tags.

**Comment by erikw** [comment]
@stsewd thanks for your support! 

The following worked for me.
```bash
$ mkdir -p $XDG_CONFIG_HOME/nvim/queries/comment
$ touch $XDG_CONFIG_HOME/nvim/queries/comment/highlights.scm
```

and set `highlights.scm` to the contents:
```scheme
("text" @text.warning
 (#any-of? @text.warning "NOTE" ))
```

What do you think about adding this to tree-sitter-comment directly? To make it consistent with that how TODO markers are recognized [also without trailing colon]?

**Comment by stsewd** [comment]
> What do you think about adding this to tree-sitter-comment directly? To make it consistent with that how TODO markers are recognized [also without trailing colon]?

I think it makes sense to have it upstream, feel free to open a PR and see what the others think.
