### ISSUE TITLE
Highlight URI's in comments

### ISSUE THREAD

**Issue by yochem** [stsewd/tree-sitter-comment#15]
Hi, 

I don't know if this is the right place to ask, but I figured you might know the solution. I would like to highlight URI's in comments, so far, I've tried the following:

```scm
("text" @text.uri @nospell
 (#lua-match? @text.uri "[a-z]*://[^ >,;]*"))
```
I verified the lua pattern:
```lua
> string.match('# TODO: test https://twitter.com test', "[a-z]*://[^ >,;]*")
https://twitter.com
```
But still nothing:
![image](https://user-images.githubusercontent.com/23235841/222172119-87650a87-799e-45e2-b4ab-2077691351be.png)

What's weird, is that if I try to do for example only 'http', like so:
```scm
("text" @text.uri @nospell
 (#lua-match? @text.uri "http"))
```
It works:
![image](https://user-images.githubusercontent.com/23235841/222172415-baf9a146-bf33-40b4-a470-d2861c5932c6.png)

Could it be because `:` is a node or something in the comment grammar?

**Comment by stsewd** [comment]
Hi, so all text nodes are delimited by punctuation symbols (so we can detect things like `(TODO: ...).TODO:..`

To highlight the whole URL, you may try to match each individual part, like

```
("text" @_a @text.note . "text" @_b @text.note . "text" @_c @text.note (#match? @_a "^https?$") (#match? @_b "^:$") (#match? @_c "^/$"))
```

But adding support for URLs is something I wanted to add https://github.com/stsewd/tree-sitter-comment#todo, but wasn't sure if it would be okay to include.

**Comment by yochem** [comment]
Thanks! Will try it out. I think it would be very nice to include url's. I was also thinking about including something like a code node for text in backticks, but that might be too markdown-like.
