### ISSUE TITLE
Heavy performance regression for block-comments

### ISSUE THREAD

**Issue by tobealive** [stsewd/tree-sitter-comment#17]
Using the comment parser with block comments results in heavy performance regressions. E.g. when scrolling (`<C-d>` / `<C-u>`) the commented section.

I'm ignoring the comment parser in ts_config for the last 6 months or so to not experience this issue. But re-testing it, it's still present.
```lua
-- List of parsers to ignore installing
-- "comment" results in major performance issues when using block comments.
-- ignore_install = { "comment" },
```

It would be great to have it solved and to be able to use this parser unimpaired.

It's probably a global issue, but during a short re-test the regression is definitively present in rust, lua.

**Comment by stsewd** [comment]
Hi, this is a neovim problem https://github.com/neovim/neovim/issues/22426, also make sure you are using the nightly version of neovim.

**Comment by tobealive** [comment]
Thanks for the quick response and referencing the related issue, wasn't aware about this!

Yep, nightly all the way :shipit: :+1:

**Comment by stsewd** [comment]
Closing this, since isn't related to the grammar itself, but neovim.
