### ISSUE TITLE
Enhancement: also highlight FIXME and XXX

### ISSUE THREAD

**Issue by craigmac** [stsewd/tree-sitter-comment#19]
FIXME and XXX are both highlighted in Vim's traditional syntax highlighting, along with TODO, can we add them to match what Vim does?

**Comment by stsewd** [comment]
Hi, this is already supported out of the box with nvim-treesitter

https://github.com/nvim-treesitter/nvim-treesitter/blob/8ec9a50965ccd34d504db86f09c580edfcff0c0f/queries/comment/highlights.scm#L18-L19

https://github.com/nvim-treesitter/nvim-treesitter/blob/8ec9a50965ccd34d504db86f09c580edfcff0c0f/queries/comment/highlights.scm#L36-L37

You are probably not using the comment parser, make sure you have it installed.
