### ISSUE TITLE
Not working with PHP in neovim

### ISSUE THREAD

**Issue by danrot** [stsewd/tree-sitter-comment#25]
I have installed this grammar in neovim, and would like to use it in PHP. It seems to work in lua:

<img width="152" alt="grafik" src="https://github.com/stsewd/tree-sitter-comment/assets/405874/a34af117-982b-4ba8-9209-1a6679b7e47e">

However, adding a TODO comment in a PHP file does not work:

<img width="136" alt="grafik" src="https://github.com/stsewd/tree-sitter-comment/assets/405874/39f05a37-5908-4642-83fc-64ae85ab195c">

Should this grammar work with every language? I have no idea why it works in Lua but not in PHP...

**Comment by stsewd** [comment]
Hi, this is because PHP doesn't use the comment parser in PHP comments, but it uses the phpdoc parser, see https://github.com/nvim-treesitter/nvim-treesitter/pull/2280. You could try extending the injections to add the comment grammar, or maybe suggest the change upstream.
