### ISSUE TITLE
Transfer repo to tree-sitter-grammars org?

### ISSUE THREAD

**Issue by clason** [stsewd/tree-sitter-comment#36]
Hi @stsewd 

You may have seen that some tree-sitter and nvim-treesitter maintainers have created a https://github.com/tree-sitter-grammars org to better streamline parser maintenance through consistent workflows, releases, and adaptation to breaking upstream changes. (For example, this parser currently fails to `:TSInstallFromGrammar` due to a package.json that no longer satisfies the stricter requirements. The ecosystem is also moving towards versioned releases with automated (wasm) parser artefacts.)

Would you be interested in moving the parser to the org? (You'd keep write but not admin permissions, by default.)  If so, it'd be easiest to transfer the repo to me and I'll transfer it to the org. If not, no problem either -- it's an offer to help with maintenance, not a request!

**Comment by stsewd** [comment]
Hi, thanks for reaching out. I may have to think more about this decision. I'm going to be off next week, and then traveling some more, so I may be slow to reply for some weeks.

**Comment by stsewd** [comment]
> For example, this parser currently fails to :TSInstallFromGrammar due to a package.json that no longer satisfies the stricter requirements.

In the meantime, I'm happy to review any PRs that fix those type of things.

**Comment by clason** [comment]
I'll take this as a "no" :) (The offer still stands, should you ever reconsider!)
