### ISSUE TITLE
[Rust]: Highlight "safety comments"

### ISSUE THREAD

**Issue by Some-Dood** [stsewd/tree-sitter-comment#7]
Hello there! It was mentioned in the README that this project is open to suggestions regarding popular comment conventions in other languages. I would like to propose adding highlighting support for "safety comments", a convention that is particularly prevalent among Rust programmers. Safety comments communicate why certain usage of [`unsafe` code](https://doc.rust-lang.org/book/ch19-01-unsafe-rust.html) indeed does not violate invariants relied upon by the compiler and depended libraries. An example of such usage is given below:

```rust
let mut text: String = get_string_from_somwhere();
if text.is_ascii() {
    // SAFETY: We have verified that all characters are within the ASCII range.
    // Thus, the following byte-wise operations preserve UTF-8-validity.
    let bytes = unsafe { text.as_bytes_mut() };
    // Do aforementioned byte-wise operations here...
}
```

As illustrated above, the keyword I am proposing to add is `SAFETY`. It would be really neat for safety comments to pop out considering how critical they are to enforcing correctness in code. Thanks!

**Comment by stsewd** [comment]
Hi, this case is already covered by the current syntax https://github.com/stsewd/tree-sitter-comment#syntax

For example, using nvim-treesitter you get this

![Screenshot from 2021-07-06 10-55-15](https://user-images.githubusercontent.com/4975310/124631119-b0ca6d80-de48-11eb-87ba-e0349ca37c75.png)

**Comment by Some-Dood** [comment]
That's strange... Mine doesn't get highlighted. I'm currently using the latest stable Neovim (v0.5.0). Running `:checkhealth nvim-treesitter` and `:checkhealth treesitter` don't indicate any errors as well. As far as I know, I have enabled the highlighting module. Is there some configuration option I may have missed?

```lua
require'nvim-treesitter.configs'.setup {
    highlight = { enable = true }
}
```

Also, thanks for the quick response!

**Comment by stsewd** [comment]
@Some-Dood do you have the comment parser installed? That's `:TSInstall comment`, it could also have been overridden by the colorsheme you are using.

**Comment by Some-Dood** [comment]
Yup, `:TSInstall comment` compiles just fine. And yes, you are correct about the color scheme. During the upgrade to the stable v0.5.0, I have forgotten to migrate to the modern color schemes for the One Dark theme. Indeed, as soon as I switched over, everything worked as expected. Thank you very much for your help!
